name: "My Custom Python and Shell Action"
description: "A custom GitHub Action to run my Python and shell code"
runs:
  using: "composite"
  steps:
    - name: Run Python shell
      shell: python
      run: |
        print(f"Hello world")

    - name: Where are you?
      shell: bash
      run: pwd

    - name: Generate payload
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python generate_payload.py
